#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$artisan = new TwoThirds\ArtisanAnywhere\Artisan(__DIR__);

$artisan->registerCommands([
    Illuminate\Foundation\Console\TestMakeCommand::class,
]);

exit($artisan->handle());
